<?php

namespace Database\Seeders;

use App\Models\AdminCompany;
use App\Models\AdminSaas;
use App\Models\Company;
use App\Models\Customer;
use App\Models\Employee;
use App\Models\SaasConfig;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DemoSeeder extends Seeder
{
    public function run(): void
    {
        AdminSaas::query()->insert([
            [
                'id' => Str::uuid(),
                'name' => 'Super Admin Demo',
                'email' => 'superadmin@demo.test',
                'phone_country_code' => '+62',
                'phone_number' => '81111111111',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Admin Operator Demo',
                'email' => 'admin@demo.test',
                'phone_country_code' => '+62',
                'phone_number' => '82222222222',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $companies = [
            ['id' => Str::uuid(), 'name' => 'PT Net Sejahtera Abadi', 'email' => 'info@netsejahtera.com', 'phone_country_code' => '+62', 'phone_number' => '82112345678', 'is_active' => true],
            ['id' => Str::uuid(), 'name' => 'CV Digital Media Nusantara', 'email' => 'admin@digitalmedia.id', 'phone_country_code' => '+62', 'phone_number' => '82187654321', 'is_active' => true],
            ['id' => Str::uuid(), 'name' => 'UD Net Mandiri Global', 'email' => 'support@netmandiri.com', 'phone_country_code' => '+62', 'phone_number' => '82211223344', 'is_active' => false],
            ['id' => Str::uuid(), 'name' => 'PT Jaringan Prima', 'email' => 'halo@jaringanprima.com', 'phone_country_code' => '+62', 'phone_number' => '82244332211', 'is_active' => true],
            ['id' => Str::uuid(), 'name' => 'CV Angkasa Netindo', 'email' => 'info@angkanet.id', 'phone_country_code' => '+62', 'phone_number' => '82255667788', 'is_active' => true],
        ];

        foreach ($companies as $company) {
            $company['created_at'] = now();
            $company['updated_at'] = now();
            Company::query()->insert($company);
        }

        SaasConfig::query()->insert([
            [
                'id' => Str::uuid(),
                'key' => 'contact.phone',
                'type' => 'text',
                'value' => '+62 812-3456-7890',
                'descripton' => 'Nomor telepon kontak utama halaman Hubungi Kami',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.email',
                'type' => 'text',
                'value' => 'support@rtrwnet.id',
                'descripton' => 'Email kontak utama halaman Hubungi Kami',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.address',
                'type' => 'text',
                'value' => 'Jl. Teknologi No. 10, Jakarta Selatan, DKI Jakarta 12950',
                'descripton' => 'Alamat kantor halaman Hubungi Kami',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.working_schedule',
                'type' => 'text',
                'value' => "Senin — Jumat: 08:00 — 20:00 WIB\nSabtu: 09:00 — 15:00 WIB",
                'descripton' => 'Jadwal operasional lengkap (bisa termasuk hari libur, akhir pekan, 24/7)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.whatsapp',
                'type' => 'text',
                'value' => '+62 812-3456-7890',
                'descripton' => 'Nomor WhatsApp kontak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'company.email',
                'type' => 'text',
                'value' => 'support@erprtrw.net',
                'descripton' => 'Email perusahaan untuk halaman error',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'company.phone',
                'type' => 'text',
                'value' => '+62 851-2345-6789',
                'descripton' => 'Telepon perusahaan untuk halaman error',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.email_terms',
                'type' => 'text',
                'value' => 'legal@rtrwnet.id',
                'descripton' => 'Email kontak halaman Syarat & Ketentuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'key' => 'contact.email_privacy',
                'type' => 'text',
                'value' => 'privacy@rtrwnet.id',
                'descripton' => 'Email kontak halaman Kebijakan Privasi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $company1Id = $companies[0]['id'];
        $company2Id = $companies[1]['id'];
        $company3Id = $companies[2]['id'];
        $company4Id = $companies[3]['id'];
        $company5Id = $companies[4]['id'];

        AdminCompany::query()->insert([
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Admin Net Sejahtera',
                'email' => 'admin@netsejahtera.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345670',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Admin Digital Media',
                'email' => 'admin@digitalmedia.id',
                'phone_country_code' => '+62',
                'phone_number' => '82187654320',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company3Id,
                'name' => 'Admin Net Mandiri',
                'email' => 'admin@netmandiri.com',
                'phone_country_code' => '+62',
                'phone_number' => '82211223340',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Admin Jaringan Prima',
                'email' => 'admin@jaringanprima.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332210',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Admin Angkasa Netindo',
                'email' => 'admin@angkanet.id',
                'phone_country_code' => '+62',
                'phone_number' => '82255667780',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Employee::query()->insert([
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmad@netsejahtera.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345671',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Siti Nuraini',
                'email' => 'siti@netsejahtera.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345672',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Budi Santoso',
                'email' => 'budi@netsejahtera.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345673',
                'is_active' => false,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Dewi Lestari',
                'email' => 'dewi@digitalmedia.id',
                'phone_country_code' => '+62',
                'phone_number' => '82187654321',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Rudi Hermawan',
                'email' => 'rudi@digitalmedia.id',
                'phone_country_code' => '+62',
                'phone_number' => '82187654322',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Hendra Gunawan',
                'email' => 'hendra@jaringanprima.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332211',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Ratna Sari',
                'email' => 'ratna@jaringanprima.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332212',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Andi Prasetyo',
                'email' => 'andi@angkanet.id',
                'phone_country_code' => '+62',
                'phone_number' => '82255667781',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Maya Indah',
                'email' => 'maya@angkanet.id',
                'phone_country_code' => '+62',
                'phone_number' => '82255667782',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Customer::query()->insert([
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Pak Sugeng',
                'email' => 'sugeng@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345681',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Melati No. 12, RT 03 RW 05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Bu Rini',
                'email' => 'rini@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345682',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Anggrek No. 5, RT 02 RW 05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Pak Herman',
                'email' => 'herman@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345683',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Mawar No. 8, RT 01 RW 05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company1Id,
                'name' => 'Mbak Dewi',
                'email' => 'dewi.w@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82112345684',
                'is_active' => false,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Kenanga No. 3, RT 04 RW 05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Pak Slamet',
                'email' => 'slamet@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82187654331',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Cendana No. 10, RT 02 RW 03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Bu Tuti',
                'email' => 'tuti@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82187654332',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Cempaka No. 7, RT 01 RW 03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company2Id,
                'name' => 'Pak Joko',
                'email' => 'joko@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82187654333',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Dahlia No. 15, RT 03 RW 03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Pak Wahyu',
                'email' => 'wahyu@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332221',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Flamboyan No. 2, RT 05 RW 02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Bu Ani',
                'email' => 'ani@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332222',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Asoka No. 11, RT 05 RW 02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company4Id,
                'name' => 'Pak Dodi',
                'email' => 'dodi@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82244332223',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Teratai No. 6, RT 06 RW 02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Pak Ujang',
                'email' => 'ujang@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82255667791',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Bougenville No. 9, RT 01 RW 07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Bu Lilis',
                'email' => 'lilis@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82255667792',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Nusa Indah No. 4, RT 02 RW 07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'company_id' => $company5Id,
                'name' => 'Pak Cecep',
                'email' => 'cecep@gmail.com',
                'phone_country_code' => '+62',
                'phone_number' => '82255667793',
                'is_active' => true,
                'password' => bcrypt('password123'),
                'address' => 'Jl. Edelweis No. 13, RT 03 RW 07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $this->call(PermissionSeeder::class);
    }
}
