<script setup>
import { ref } from 'vue';
import CustomerLayout from '@/Layouts/CustomerLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
defineOptions({ layout: CustomerLayout });
const form = ref({ nama_paket: '', kecepatan: '', harga: '', fup: '' }); const formErrors = ref({});
function validateForm() { const e = {}; if (!form.value.nama_paket.trim()) e.nama_paket = 'Nama paket wajib diisi'; formErrors.value = e; return Object.keys(e).length === 0; }
</script>
<template>
  <div><Head title="Tambah Paket | Pelanggan" /><slot name="header">Tambah Paket</slot>
    <div class="space-y-6">
      <nav class="flex items-center gap-1.5 text-sm"><Link href="/customer/dashboard" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors"><i class="fas fa-home"></i></Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><Link href="/customer/dashboard" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors">Dashboard</Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><Link href="/customer/paket-saya" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors">Paket Saya</Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><span class="text-gray-900 dark:text-white font-medium">Tambah</span></nav>
      <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-sm p-6 sm:p-8 max-w-lg"><form class="space-y-4" @submit.prevent=""><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Nama Paket <span class="text-red-500">*</span></label><input v-model="form.nama_paket" type="text" placeholder="Contoh: Gold 50Mbps" :class="['w-full px-3 py-2.5 rounded-lg border text-sm outline-none transition-colors bg-white dark:bg-gray-900 text-gray-900 dark:text-white', formErrors.nama_paket ? 'border-red-400 focus:ring-red-500 focus:border-red-500' : 'border-gray-300 dark:border-gray-600 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500']" /><p v-if="formErrors.nama_paket" class="text-red-500 text-xs mt-1">{{ formErrors.nama_paket }}</p></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Kecepatan (Mbps)</label><input v-model="form.kecepatan" type="number" min="1" class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none transition-colors" /></div><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Harga (Rp)</label><input v-model="form.harga" type="number" min="0" class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none transition-colors" /></div></div><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">FUP (GB)</label><input v-model="form.fup" type="text" placeholder="Contoh: 500" class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none transition-colors" /></div><div class="flex justify-end gap-2 pt-2"><Link href="/customer/paket-saya" class="px-4 py-2.5 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">Batal</Link><button type="submit" class="px-6 py-2.5 bg-emerald-600 text-white text-sm font-medium rounded-lg hover:bg-emerald-700 transition-colors shadow-sm"><i class="fas fa-save mr-1.5"></i> Simpan</button></div></form></div>
    </div>
  </div>
</template>
