<script setup>
import { ref } from 'vue';
import CustomerLayout from '@/Layouts/CustomerLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
defineOptions({ layout: CustomerLayout });
const form = ref({ kode_tagihan: '', jumlah: '', metode: 'Transfer', tgl_bayar: '' }); const formErrors = ref({});
function validateForm() { const e = {}; if (!form.value.kode_tagihan.trim()) e.kode_tagihan = 'Kode tagihan wajib diisi'; if (!form.value.jumlah || Number(form.value.jumlah) <= 0) e.jumlah = 'Jumlah tidak valid'; if (!form.value.tgl_bayar) e.tgl_bayar = 'Tanggal bayar wajib diisi'; formErrors.value = e; return Object.keys(e).length === 0; }
</script>
<template>
  <div><Head title="Tambah Pembayaran | Pelanggan" /><slot name="header">Tambah Pembayaran</slot>
    <div class="space-y-6">
      <nav class="flex items-center gap-1.5 text-sm"><Link href="/customer/dashboard" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors"><i class="fas fa-home"></i></Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><Link href="/customer/dashboard" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors">Dashboard</Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><Link href="/customer/riwayat-pembayaran" class="text-gray-500 dark:text-gray-400 hover:text-emerald-600 transition-colors">Riwayat Pembayaran</Link><i class="fas fa-chevron-right text-[10px] text-gray-400 dark:text-gray-500"></i><span class="text-gray-900 dark:text-white font-medium">Tambah</span></nav>
      <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-sm p-6 sm:p-8 max-w-lg"><form class="space-y-4" @submit.prevent="">
        <div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Kode Tagihan <span class="text-red-500">*</span></label><input v-model="form.kode_tagihan" type="text" placeholder="INV-202505-001" :class="['w-full px-3 py-2.5 rounded-lg border text-sm outline-none transition-colors bg-white dark:bg-gray-900 text-gray-900 dark:text-white font-mono', formErrors.kode_tagihan ? 'border-red-400 focus:ring-red-500 focus:border-red-500' : 'border-gray-300 dark:border-gray-600 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500']" /><p v-if="formErrors.kode_tagihan" class="text-red-500 text-xs mt-1">{{ formErrors.kode_tagihan }}</p></div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Jumlah (Rp) <span class="text-red-500">*</span></label><input v-model="form.jumlah" type="number" min="0" :class="['w-full px-3 py-2.5 rounded-lg border text-sm outline-none transition-colors bg-white dark:bg-gray-900 text-gray-900 dark:text-white', formErrors.jumlah ? 'border-red-400 focus:ring-red-500 focus:border-red-500' : 'border-gray-300 dark:border-gray-600 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500']" /><p v-if="formErrors.jumlah" class="text-red-500 text-xs mt-1">{{ formErrors.jumlah }}</p></div><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Tanggal Bayar <span class="text-red-500">*</span></label><input v-model="form.tgl_bayar" type="date" :class="['w-full px-3 py-2.5 rounded-lg border text-sm outline-none transition-colors bg-white dark:bg-gray-900 text-gray-900 dark:text-white', formErrors.tgl_bayar ? 'border-red-400 focus:ring-red-500 focus:border-red-500' : 'border-gray-300 dark:border-gray-600 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500']" /><p v-if="formErrors.tgl_bayar" class="text-red-500 text-xs mt-1">{{ formErrors.tgl_bayar }}</p></div></div>
        <div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Metode</label><select v-model="form.metode" class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none transition-colors"><option value="Tunai">Tunai</option><option value="Transfer">Transfer</option><option value="QRIS">QRIS</option></select></div>
        <div class="flex justify-end gap-2 pt-2"><Link href="/customer/riwayat-pembayaran" class="px-4 py-2.5 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">Batal</Link><button type="submit" class="px-6 py-2.5 bg-emerald-600 text-white text-sm font-medium rounded-lg hover:bg-emerald-700 transition-colors shadow-sm"><i class="fas fa-save mr-1.5"></i> Simpan</button></div>
      </form></div>
    </div>
  </div>
</template>
