name: Add issues to project

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_url:
        description: 'Issue URL to add'
        required: false
        type: string

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      projects: write
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/mascahyo1/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-url: ${{ inputs.issue_url || github.event.issue.html_url }}
